ifeq ($(findstring 86, $(ProgramFiles)), )
	PROGFILES := C:/Program Files
else
	PROGFILES := C:/Program Files (x86)
endif

#GNU_INSTALL_ROOT := $(PROGFILES)/GNU Tools ARM Embedded/4.9 2015q1
#GNU_VERSION := 4.9.3
GNU_INSTALL_ROOT := C:/dev/gcc-arm-none-eabi
GNU_VERSION := 5.3.1
GNU_PREFIX := arm-none-eabi

